# output_dir: '../kilosim-gridbots-decisions/imgs/'
output_dir: '../grid-decisions/test-imgs/'

# Allowed parameters to include in the filename format are:
# - frequency (same as parameter below)
# - octaves
# - persistence
# - lacunarity
# - img_ind (index of image, as configured by num_imgs and img_ind_offset)
# img_filename_format: '{img_ind:03d}_oct={octaves}'
img_filename_format: 'img_oct={octaves}_{img_ind:03d}'

allow_overwrite: true

img_dim: [384,384]
num_imgs: 5
# num_imgs: 100
img_ind_offset: 1

frequency: 200 # Starting frequency
octaves: [1,3,5] # Number of iterations
persistence: 0.5 # How intensity changes with each octave
lacunarity: 2.1 # How scale changes with each octave

make_valleys: false